const items = [
  {
    id: 1,
    name: 'vivo',
    title: 'vivo T2x 5G (Marine Blue, 128 GB)  (6 GB RAM)',
    price: 19.99,
    active: false,
    img: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/k/u/n/-original-imagzjhwtfthcmzz.jpeg?q=70', 
  },
  {
    id: 2,
    name: 'vivo',
    title: 'vivo T2 5G (Velocity Wave, 128 GB)  (6 GB RAM)',
    description: 'Description for Product 2',
    price: 29.99,
    active: false,
    img: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/r/s/r/-original-imagpfbtmrr7spgc.jpeg?q=70', 
  },
  {
    id: 3,
    name: 'Motorola',
    title: 'MOTOROLA g14 (Butter Cream, 128 GB)  (4 GB RAM)',
    description: 'Description for Product 3',
    price: 39.99,
    active: false,
    img: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/n/f/n/-original-imagsmshun6anugu.jpeg?q=70', 
  },
  {
    id: 4,
    name: 'Redmi',
    title: 'REDMI 12 (Moonstone Silver, 128 GB)  (6 GB RAM)',
    description: 'Description for Product 3',
    price: 39.99,
    active: false,
    img: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/k/j/n/-original-imags37gyajqxkgp.jpeg?q=70', 
  },
  {
    id: 5,
    name: 'Redmi',
    title: 'REDMI 12C (Matte Black, 64 GB)  (4 GB RAM)',
    description: 'Description for Product 3',
    price: 39.99,
    active: false,
    img: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/q/b/i/-original-imagvyp8pjedpxsj.jpeg?q=70', 
  },
  {
    id: 6,
    name: 'Oneplus',
    title: 'OnePlus Nord CE 2 Lite 5G (Blue Tide, 128 GB)  (6 GB RAM)',
    description: 'Description for Product 3',
    price: 39.99,
    active: false,
    img: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/2/p/8/-original-imagg2a4rmk94gay.jpeg?q=70', 
  },
  {
    id: 7,
    name: 'vivo',
    title: 'vivo T2 Pro 5G (New Moon Black, 256 GB)  (8 GB RAM)',
    description: 'Description for Product 3',
    price: 39.99,
    active: false,
    img: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/g/b/x/-original-imagtt4h4ptmxgwn.jpeg?q=70', 
  },
  {
    id: 8,
    name: 'Redmi',
    title: 'REDMI 12 (Jade Black, 128 GB)  (6 GB RAM)',
    description: 'Description for Product 3',
    price: 39.99,
    active: false,
    img: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/h/f/w/-original-imags37hy7uz2usv.jpeg?q=70', 
  },
  {
    id: 9,
    name: 'Poco',
    title: 'POCO C51 (Royal Blue, 128 GB)  (6 GB RAM)',
    description: 'Description for Product 3',
    price: 39.99,
    active: false,
    img: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/6/v/0/c51-mzb0dxkin-poco-original-imagzdpycgrcdc8z.jpeg?q=70',
  },
  {
    id: 10,
    name: 'Motorola',
    title: 'MOTOROLA e13 (Aurora Green, 128 GB)  (8 GB RAM)',
    description: 'Description for Product 3',
    price: 39.99,
    active: false,
    img: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/s/y/n/-original-imagshuzkeurgwd8.jpeg?q=70', 
  },

];

export default items;
